name: Generate Snake

on:
  schedule: # roda a cada 12h
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 🔑 permite criar/atualizar branch output

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: PedroOBertoni
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Snake"
          add: "dist/*.svg"
          branch: output
